### PR TITLE
Fixes to RBAC

### PR DESCRIPTION
**Pull request by wintrov**
Fixed the issues with the string, changing from string to list type.
Change back to imageTag: 0.10.1 since 0.11.0 doesn't work with existing RBAC

### CODE REVIEW

**Comment by christianknell** [comment]
@wintrov why doesn't it work with v0.11.0?

**Comment by wintrov** [comment]
> @wintrov, why doesn't it work with v0.11.0?

For some reason, it didn't work for me in this version with the RBAC
only 0.10.1 with these RBAC worked for me.

**Comment by christianknell** [comment]
@wintrov how did you run the chart? Can you provide your values please?

**Comment by wintrov** [comment]
> @wintrov how did you run the chart? Can you provide your values please?

@christianknell 
attached an image
this is a log from the application
Screenshot 2023-02-19 at 11 50 12

**Comment by christianknell** [comment]
@wintrov fixed with the latest popeye-release v.0.11.1. Can you explain why you added additional permissions to the ClusterRole?

**Comment by christianknell** [comment]
@saar-win thanks. Will merge this today.

**Comment by christianknell** [comment]
@wintrov has been released with a seperate mr. Thanks for your contribution!

**Pull request closed without merging**
